#!/bin/sh
set -e

case "$1" in
	remove|purge)
		echo -n "Removing service logs..."
		rm /var/log/thingsplex/panasonic-comfort-cloud/* || true
		echo "...OK"
		echo -n "Removing service configuration and data files..."
		rm /opt/thingsplex/panasonic-comfort-cloud/data/* || true
		echo "...OK"
	;;

	upgrade|abort-upgrade|abort-install|failed-upgrade|disappear)
	;;

	*)
		echo "postrm called with an unknown argument \`$1'" >&2
		exit 1
	;;
esac

exit 0