name: CI

on:
  push:
    branches:
    - main
    tags:
    - "v*"
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      actions: read
      contents: write
      checks: write
      statuses: write
      id-token: write

    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go 1.x
      uses: actions/setup-go@v4
      with:
        go-version-file: 'src/go.mod'
        # cache: true

    - name: Lint
      run: |
        make lint

    - name: Test
      run: |
        docker-compose up -d
        make test

    - name: Build
      run: |
        make build-go
